FROM gitpod/workspace-mysql

RUN apt-get update
RUN apt-get install -y python
RUN apt-get install -y python-pip

RUN pip install MySQL-python==1.2.5
RUN pip install web.py==0.38
RUN pip install pyopenssl >= 17.5.0
